### ISSUE TITLE
Опция для подключения стандартной библиотеки шагов от 1bdd

### ISSUE THREAD

**Issue by artbear** [artbear/1bdd#101]
Хотелось бы, чтобы учитывались стандартные шаги, которые есть в 1bdd (из каталог features)
ключ "1bdd exec path -standard-steps"

**Comment by artbear** [comment]
@nixel2007 что скажешь?

Например, у меня в стандартных шагах есть полезные шаги 
+ `в лог-файле запуска продукта есть строка "ЯЗапускаюПадающийШагСПараметром-Первый падающий шаг"`
+ в лог-файле запуска продукта отсутствует строка "ДоЭтогоШагаВыполнениеДойтиНеДолжно"
+ 'в файле "clean.log" есть строка "ыва"'

хотелось бы их применить в фичах других проектов, например, gitsync

**Comment by nixel2007** [comment]
предлагаю сначала выделить их в features/library, по аналогии с VB. и только их подключать.
