### ISSUE TITLE
Стандартные шаги для файловых операций

### ISSUE THREAD

**Issue by artbear** [artbear/1bdd#104]

**Comment by nixel2007** [comment]
в чем разница между текущим каталогом и рабочим?

**Comment by nixel2007** [comment]
p.s. ты бы релизы почаще выпускал

**Comment by artbear** [comment]
Текущий каталог это CWD, а рабочий каталог может быть произвольным, смены CWD не происходит

ЗЫ Релизы выпущу. Пока 10 дней просрочено :)
