### ISSUE TITLE
Добавить шаблоны при передаче параметров в команду внутри шагов

### ISSUE THREAD

**Issue by artbear** [artbear/1bdd#107]
Например, сейчас нельзя разрулить ситуацию для vanessa-runner
```gherkin
    Когда Я установил рабочий каталог как текущий каталог
    И Я выполняю команду "oscript" c параметрами "tools/init.os init-dev --src ./cf --ibname /F build/ib "
    Тогда Я сообщаю вывод команды "oscript"
```

Непонятно, как шагу передать данные о пути к `tools/init.os`

Пока придумал добавить шаблоны в строке параметров для команды
Например, `<КаталогПроекта>` или `<РабочийКаталог>`
```gherkin
    Когда Я установил рабочий каталог как текущий каталог
    И Я выполняю команду "oscript" c параметрами "<КаталогПроекта>/tools/init.os init-dev --src ./cf --ibname /F build/ib "
    Тогда Я сообщаю вывод команды "oscript"
```

/cc @nixel2007 Что скажешь?

**Comment by nixel2007** [comment]
Ты проблему из воздуха создаешь имхо)
вся вот эта магия должна вызываться из корректного CWD. корректный CWD по умолчанию - каталог проекта. Если у запускаемого скрипта некорретный CWD - это проблемы запускаемого скрипта.

**Comment by artbear** [comment]
>вся вот эта магия должна вызываться из корректного CWD. корректный CWD по умолчанию - каталог проекта. Если у запускаемого скрипта некорретный CWD - это проблемы места запускаемого скрипта, и это место надо изменить.

Не-не.
У тебя есть 2 каталога - каталог проекта и временный/рабочий каталог.
Пусть, как ты и говоришь, каталог проекта является CWD.

Как теперь в шаге вызова команды обратиться к рабочему каталогу??

`.` и `..`, как и другие относительные пути, мы юзать не можем, потому что они будут связаны с каталогом проекта, как CWD.

Как??

**Comment by artbear** [comment]
Что указать для шага
`И Я выполняю команду "oscript" c параметрами "tools/init.os init-dev --src ???/cf --ibname /F ???/build/ib "
`
вместо ???
