### ISSUE TITLE
При перегенерации файла шагов добавляется пустая строка

### ISSUE THREAD

**Issue by realMaxA** [artbear/1bdd#122]
При повторной генерации файла шагов в конце файла шагов всегда добавляется пустая строка.
Проявление: если feature-файл не был изменён, и была выполнена генерация файла шагов, то в уже сгенерированном файле шагов в конце появляется ещё одна пустая строка.
Ожидаемое поведение: Файл шагов не должен меняться.

**Comment by artbear** [comment]
Исправлено давно
