### ISSUE TITLE
Ошибка при генерации файла шагов

### ISSUE THREAD

**Issue by realMaxA** [artbear/1bdd#124]
При генерации файла шагов командой `1bdd gen features` возникает ошибка

```
ОШИБКА   - {Модуль C:\Program Files (x86)\OneScript\lib\1bdd\src\bdd-generate.os / Ошибка в строке: 45 / Значение не является значением объектного типа}
```

При этом файл шагов создаётся, видимых проблем не возникает.

Данное поведение проявляется при генерации файла шагов из любого feature-файла, даже самого простого, независимо от того, повторно он генерируется или в первые.

Ожидаемое поведение: Выполнение команды не должно выводить ошибок.

**Comment by artbear** [comment]
Проблема в строке 
```bsl
РезМассивФайлов.Добавить(СоздатьФайлРеализацииШагов(ФайлФичи, НаборБиблиотечныхШагов));
```
Если ее разделить на 2 строки
```bsl
		ФайлРеализации = СоздатьФайлРеализацииШагов(ФайлФичи, НаборБиблиотечныхШагов);
		РезМассивФайлов.Добавить(ФайлРеализации);
```
то проблема исчезает.
Похоже, что какая-то проблема движка :(
У меня 1скрипт 1.0.19.92
