### ISSUE TITLE
Шаг "Я выполняю команду" должен учитывать наличие пробела

### ISSUE THREAD

**Issue by nixel2007** [artbear/1bdd#128]
Если выполняемая команда содержит пробел (например использование синтаксиса "строки запуска" - Я выполняю команду "ovm ls"), то объект Команда должен инициализироваться не через УстановитьПриложение, а через УстановитьСтрокуЗапуска.

В обратном случае это приводит к ошибке излишнего оборачивания в кавычки на уровне 1commands - https://github.com/artbear/1commands/blob/master/src/%D0%9A%D0%BE%D0%BC%D0%B0%D0%BD%D0%B4%D0%B0.os#L340 и как следствие - `ovm ls not found`

Альтернативный вариант - убрать из 1commands проверку на флаг, оставив проверку на пробел.

**Comment by artbear** [comment]
В твоих предложениях не учитывается сценарий: выполняется команда с пробелом в имени, например, с путем из program files.

1коммандс менять не вариант с учетом этого сценария.
По 1бдд думаю, как сделать удобнее.

Если я не ошибаюсь, при УстановитьСтрокуЗапуска в 1коммандс не учитываются ранее переданные параметры, что важно для шагов 1бдд.

Пока код не могу посмотреть, сижу за телефоном.

**Comment by artbear** [comment]
Разобрался.
Исправил возникающие проблемы при запуске команды с параметрами в шаге "Я выполняю команду ..."
Использую Команда.УстановитьСтрокуЗапуска вместо Команда.УстановитьКоманду
