### ISSUE TITLE
Исправить опечатку (английская с) в шаге "Я выполняю команду "" с параметрами"

### ISSUE THREAD

**Issue by artbear** [artbear/1bdd#132]
Исходный ишуз https://github.com/artbear/1bdd/issues/129

- [ ] Проверить  разные продукты

Исправить шаг + зависимость от правильного релиза 1bdd
- [ ] `oscript-app-template`

- [ ] `gitsync`

- [ ] `vanessa-runner`

- [ ] opm ?

- [ ] 1cli ?

@nixel2007 @khorevaa Еще в каких свои продуктах юзаете такой шаг?

**Comment by nixel2007** [comment]
Я отказался от его использования в ovm и написал свой.

**Comment by artbear** [comment]
Давно исправлено.
