### ISSUE TITLE
Падает тест junit

### ISSUE THREAD

**Issue by zeratulayuris** [artbear/1bdd#147]
В фиче core/junit-xml.feature падают все три сценария. Отладочный лог: https://gist.github.com/zeratulayuris/1ba579cfbf09e7d3c2cef5bbc59c93ac

Судя по всему, ошибка в пробелах перед закрывающим тег слешем - в фиче они есть, в отчете их нет.

osciprt 1.0.21.1, win10 pro.

**Comment by artbear** [comment]
ИМХО это зарегистированный баг 1скрипта, когда в Линуксе и Винде формируются разные закрывающие теги :(

https://github.com/EvilBeaver/OneScript/issues/817

на винде, в аппвейор тесты проходят на ура!

Хотя бы в твоем свежем ПР #148 

А у тебя на Линуксе падают?

**Comment by nixel2007** [comment]
это не баг оскрипта, это баг тестов. XML в обоих случаях валидный и проверять его надо по XSD/чтением в объектной технике, а не сравнением строк.

**Comment by zeratulayuris** [comment]
@artbear как раз на винде у меня и падают эти тесты. Имхо, Никита прав - и тот, и тот xml валидный и баг как раз в тесте. Будет время - переделаю, хочется полностью зелёную полосу )

**Comment by zeratulayuris** [comment]
И, кстати, про аппвейор в том самом моём ПР:
![image](https://user-images.githubusercontent.com/9881249/55606850-dcef7380-5793-11e9-865f-45218a2826ad.png)

**Comment by artbear** [comment]
Пришла идея - заменять лишний пробел

`СтрЗаменить(СтрокаХМЛ, " />" , "/>")`

для приемочных тестов вполне себе рабочий вариант

**Comment by artbear** [comment]
я называю это багом движка, потому что на разных платформах при одном исходном коде мы получаем разный текст файла :(

тест переделать можно и нужно.
просто такое поведение движка повышает сложность его использования :(

**Comment by zeratulayuris** [comment]
Закрываю, исправлено и влито.
