### ISSUE TITLE
В readme.md непонятно для чего

### ISSUE THREAD

**Issue by vsuh** [artbear/1bdd#45]
... `bdd.os` предназначен.
Для кого аббревиатура BDD ниочем не говорит, пройдут мимо.
Не написано, что делают команды `exec` и `generate`
Не написано, в каких каталогах какие файлы будут искаться а потом класться.

**Comment by artbear** [comment]
Спасибо, поправлю.

**Comment by artbear** [comment]
@vsuh Исправлено.
