### ISSUE TITLE
Контекст "БДД" недоступен из ПередНачаломСценария и ПослеНачалаСценария

### ISSUE THREAD

**Issue by nixel2007** [artbear/1bdd#84]

**Comment by artbear** [comment]
Поясни примером, что именно недоступно.
Объект фреймворка? или что-то еще?

**Comment by nixel2007** [comment]
БДД.СохранитьВКонтекст выкидывает исключение, что значение не является значением объектного типа.
`Сообщить(ТипЗнч(БДД))` выдает `Неопределено`
