### ISSUE TITLE
Запуск bdd.os без пути к файлу при установке через opm

### ISSUE THREAD

**Issue by nixel2007** [artbear/1bdd#88]
Хочу, чтобы после установки 1bdd через opm install из path была доступна команда `1bdd`

**Comment by artbear** [comment]
@EvilBeaver подскажи, какую последовательность действий нужно выполнить, чтобы в хабе 1скрипта появился пакет 1bdd ?

**Comment by EvilBeaver** [comment]
Собрать ospx пакет командой

    opm build <package-directory>

В текущем каталоге появится файл *.ospx
Файл прислать мне.

**Comment by artbear** [comment]
Файл отправлен Андрею

**Comment by artbear** [comment]
Призываю @EvilBeaver 
Когда опубликуешь пакет для 1bdd ?

**Comment by artbear** [comment]
И опять 
>Призываю @EvilBeaver
Когда опубликуешь пакет для 1bdd ?

**Comment by EvilBeaver** [comment]
а он в либе есть?

**Comment by artbear** [comment]
https://github.com/artbear/1bdd/issues/88#issuecomment-251999198
>Файл отправлен Андрею

ospx отправлял

**Comment by EvilBeaver** [comment]
торжественно клянусь на след. неделе внедрить скрипт @nixel2007 и опубликовать все долги в авторежиме

**Comment by nixel2007** [comment]
@EvilBeaver чо, надо все же релиз по гитраннеру сделать, да? а то мой скрипт не сможет собрать гитраннер без мастер-ветки :D

**Comment by EvilBeaver** [comment]
Не понял вопроса

**Comment by nixel2007** [comment]
@EvilBeaver скрипт сейчас собирает мастер ветку. а в гитраннере нет мастер ветки. если форкнуть гитраннер в оскрипт-лайбрари, то сборщик тупо упадет :)

**Comment by EvilBeaver** [comment]
Если он готов к публикации, то у него должна быть мастер-ветка :D

**Comment by nixel2007** [comment]
Это сделано
