### ISSUE TITLE
Использовать собственный класс для хранения временных файлов

### ISSUE THREAD

**Issue by nixel2007** [artbear/1bdd#89]
Не использовать синглтон ВременныеФайлы, а пользоваться МенеджеромВременныхФайлов

**Comment by artbear** [comment]
Я вспомнил, почему я пользуюсь именно синглтоном.

Тесты/шаги могут генерить временные файлы.
Эти файлы не всегда нужно удалять.

Мне был нужен прозрачная и удобная передача запрета удаления временных файлов в тесты/шаги.

Поэтому я  добавил режим отладки '1bdd команда -debug off' для запрета удаления временных файлов.

@nixel2007 Если предложишь другой такой же удобный вариант передачи запрета удаления в шаги/тесты, готов обсудить.

**Comment by artbear** [comment]
Если я в стартовом скрипте буду юзать свой экземпляр временных файлов, то временные файлы из тестов-шагов не будут удалены :(

**Comment by nixel2007** [comment]
> Если я в стартовом скрипте буду юзать свой экземпляр временных файлов, то временные файлы из тестов-шагов не будут удалены :(

Имхо - это беда сценария, а не раннера, разве нет?

**Comment by artbear** [comment]
Как разработчику без изменения кода шага/сценария посмотреть результаты работы сценария?
сейчас можно `1bdd Фича -debug off`
а в твоем варианте как?

**Comment by nixel2007** [comment]
Результат работы сценария проверяется в секции "Тогда" :)
Но твою позицию я понял, она имеет смысл.
