### ISSUE TITLE
Сниппеты генерятся со странными отступами

### ISSUE THREAD

**Issue by nixel2007** [artbear/1bdd#94]
Такое чувство, что это табуляция + пробел или 5 пробелов.

**Comment by artbear** [comment]
@nixel2007 Можешь подробнее описать проблему.
Не пойму, где именно у тебя странные отступы.

**Comment by artbear** [comment]
Отбой, увидел табуляцию.

**Comment by artbear** [comment]
@nixel2007 Какой отступ из пробелов выберем? штатное 1С - 4 пробела или какой-то другой вариант?

**Comment by nixel2007** [comment]
![default](https://cloud.githubusercontent.com/assets/1132840/19571478/fa51e8a4-9706-11e6-8fab-8cbe682bad09.gif)

**Comment by nixel2007** [comment]
На прошлом заседании комитета tabs vs spaces имени Евгения Сосны было установлено, что штатным для 1с отступом является символ табуляции :)

**Comment by artbear** [comment]
Ага, понял тебя.
У меня как раз юзается табуляция, но, похоже, еще пробел где-то вставляется :)
