### ISSUE TITLE
Интерфейс запуска через #Использовать

### ISSUE THREAD

**Issue by nixel2007** [artbear/1bdd#97]
Сейчас скрипт заточен под запуск из командной строки. 
Сommand line interface объединен с основной логикой, при подключении библиотеки через #Использовать произойдет инициализация скрипта параметрами командной строки (которые естественно к 1bdd никакого отношения не имеют) и скрипт упадет с ошибкой.

Нужно:
* Вынести логику cli в отдельный скрипт
* Предоставить библиотечный запуск тестов - процедуру запуска и инициализатор структуры параметров

**Comment by nixel2007** [comment]
P.S. Аналогичная задача будет и для тестраннера, как ты понимаешь.

**Comment by artbear** [comment]
@nixel2007 Можешь чуть подробнее описать задачу?

ты хочешь внутри запускатора `opm test` (спец.скрипта) вызвать `#Использовать 1bdd` и далее 
```bsl
ИсполнительБДД= Новый ИсполнительБДД(); 
ИсполнительБДД.ПроверитьФичу(Параметры ...);
```
или что-то другое?

**Comment by nixel2007** [comment]
Да, что-то такое. Но не только конкретную фичу, но и просто папку.

**Comment by nixel2007** [comment]
Вообще в идеале, конечно, предоставить интерфейс ко всем командам CLI https://github.com/artbear/1bdd/blob/develop/src/bdd.os#L69 , с отдельными наборами параметров. Но это можно повесить как tech debt. Для реализации же тестирования на данный момент нужен аналог команды "exec"

**Comment by artbear** [comment]
>Сейчас скрипт заточен под запуск из командной строки.
Сommand line interface объединен с основной логикой, при подключении библиотеки через #Использовать произойдет инициализация скрипта параметрами командной строки (которые естественно к 1bdd никакого отношения не имеют) и скрипт упадет с ошибкой.

@nixel2007 Начал заниматься этой проблемой.
А ты вообще проверял, что вышеописанные падение имеет место быть?

У меня есть сомнения.
У меня тесты (для 1testrunner) используют классы библиотеки с подключением библиотеки
Например, подключение https://github.com/artbear/1bdd/blob/develop/tests/exec-feature-tests.os#L18
и код использования класса https://github.com/artbear/1bdd/blob/develop/tests/exec-feature-tests.os#L180-L181

ИМХО проблемы на самом деле нет :)

Или описывай свой сценарий :)

**Comment by nixel2007** [comment]
Тэкс... Мой косяк, я честно не проверил кейс. Был уверен, что инициализация рухнет на этапе разбора аргументов командной строки.

Ок, я тогда попробую написать бдд-тестраннер для opm test, если все будет ок - закрою задачу.

**Comment by nixel2007** [comment]
@artbear итак.

Нарвался на какие-то проблемы при запуске каталога фич. Посмотри, пожалуйста.
Скрипт тестраннера - https://github.com/nixel2007/gitrunner/commit/30fd35c0d83206ac23bbb7b5a9d35ebebf48e1bb
Новый режим: https://github.com/oscript-library/opm/pull/10

Проблема - не находится часть библиотечных шагов + временные файлы создаются во временном каталоге. Текущая ветка develop

**Comment by nixel2007** [comment]
Логи: https://gist.github.com/nixel2007/66119b81663e57f28488b53b6bfdb5ae

**Comment by artbear** [comment]
Решили
нужно юзать код c явным указанием каталога библиотек
```bsl
#Использовать 1bdd

Процедура Запустить() Экспорт

    КаталогФич = ОбъединитьПути(".", "features");

	Файл_КаталогФич = Новый Файл(КаталогФич);
	Сообщить(Файл_КаталогФич);

	// Лог = Логирование.ПолучитьЛог("bdd");
	// Лог.УстановитьУровень(УровниЛога.Отладка);

    ИсполнительБДД = Новый ИсполнительБДД;
    ИсполнительБДД.ВыполнитьФичу(Файл_КаталогФич, Файл_КаталогФич);

КонецПроцедуры
```

**Comment by artbear** [comment]
Закрываю?

**Comment by nixel2007** [comment]
@artbear может оставим эту задачу для разработки в будущем отдельного красивого интерфейса?

**Comment by artbear** [comment]
ИМХО эту задачу лучше закрыть. В ней уже много букв, которое имеют малое отношение к новой теме :)
А вот для красивого интерфейса сделать отдельную задачу
